modules: [cpu, mem, fs]

fs:
  mountpoints: [root, home]
  root.path: "/"
  home.path: "/home"

homeassistant:
  discovery:
    prefix: homeassistant
    trigger_topic: homeassistant/status

mqtt:
  broker: "tcp://<mqtt server>:1883"
  username: <username>
  password: <password>
